replicaCount: 1

configMap:
  env: Development

image:
  name: docker.pkg.github.com/csharpey/stamp-service
  tag:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: registry-secret
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    memory: 2Gi
    cpu: 0.6
  requests:
    memory: 1Gi
    cpu: 0.4

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
