version: '2'

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
  minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio}
    volumes:
      - 'minio_data:/data'
      
  backend:
    image: ghcr.io/csharpey/stamping-service
    build:
      context: .
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5000:5000"
    networks:
      - default
    depends_on:
      - minio
volumes:
  minio_data:
    driver: local
  cache:
    driver: local 
networks:
  default:
    driver: bridge
