name: Tests

#on:
#  push:
#    branches: ["*"]
#  paths:
#    - src/**/*
#    - tests/**/*

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore --configfile NuGet.config
      - name: Test
        run: dotnet test --filter TestCategory=Unit
  integration-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:6.2-alpine
      postgres:
        image: postgres:14.2
    container: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore --configfile NuGet.config
      - name: Test
        run: dotnet test --filter TestCategory=Integration
